686Final/Controllers/ApplicationController.cs
using _686Final.Base;
using _686Final.Helper;
using Common;
using LoadersAndLogic;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace _686Final.Controllers
{
    public class ApplicationController : BaseController
    {

        AppLoader appLoader = new AppLoader();

        // GET: Application
        public ActionResult Index()
        {
            // log a error each time launch the application home page.
            // FinalLogger.finalLogger.Log("Error from Application Comtroller", 1, null);
            return View(appLoader.getAllApplications());
        }

        // GET: Application/Details/5
        public ActionResult Details(int id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ApplicationViewModel application = appLoader.getApplication(id);
            if (application == null)
            {
                return HttpNotFound();
            }
            return View(application);
        }


        // GET: Application/Edit/5
        public ActionResult Edit(int id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ApplicationViewModel application = appLoader.getApplication(id);
            if (application == null)
            {
                return HttpNotFound();
            }
            return View(application);
        }

        // POST: Application/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, [Bind(Include = "AppDescription,AppType, AppActive")] ApplicationViewModel application)
        {
            if (ModelState.IsValid)
            {
                appLoader.updateApp(id, application);
                return RedirectToAction("Index");
            }
            return View(application);
        }


        // GET: App/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: App/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "AppDescription,AppType")] ApplicationViewModel applicationViewModel)
        {
            if (ModelState.IsValid)
            {
                appLoader.createNewApp(applicationViewModel);
                return RedirectToAction("Index");
            }

            return View(applicationViewModel);
        }



    }
}

686Final/Controllers/UserController.cs
using _686Final.Base;
using Common;
using LoadersAndLogic;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace _686Final.Controllers
{
    public class UserController : BaseController
    {

        UserLoader userLoader = new UserLoader();

        // GET: User
        public ActionResult Index()
        {
            return View(userLoader.GetAllUsers());
        }

        // GET: User/User/5
        public ActionResult CurrentUser(string email)
        {
            String user = System.Web.HttpContext.Current.User.Identity.Name;
            if (user == email)
            {
                return View(userLoader.GetUserByEmail(email));
            }
            else {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
           
        }

        // GET: User/Details/5
        public ActionResult Details(int id)
        {
            UserViewModel user = userLoader.GetUserByIdForAdmin(id);
            if (user == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            else {
                return View(user);
            }
            
        }

        // GET: User/Edit/5
        public ActionResult Edit(int id)
        {
            UserViewModel user = userLoader.GetUserByIdForAdmin(id);

            if (user == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }


            List<SelectListItem> roleDescs = new List<SelectListItem>();
            userLoader.getAllRoles().ToList().ForEach(delegate (RoleViewModel item) {
                SelectListItem sItem = new SelectListItem();
                sItem.Text = item.RoleDescript;
                Debug.WriteLine(item.RoleDescript);
                sItem.Value = item.RoleID.ToString();
                if (item.RoleID == user.RoleID) {
                    sItem.Selected = true;
                    Debug.WriteLine("Default is: " + user.RoleID);
                }
                roleDescs.Add(sItem);
            });

            List<SelectListItem> stateDescs = new List<SelectListItem>();
            userLoader.getAllStates().ToList().ForEach(delegate (StateViewModel item) {
                SelectListItem sItem = new SelectListItem();
                sItem.Text = item.StateDescript;
                sItem.Value = item.StateID.ToString();
                if (item.StateID == user.StateID)
                {
                    sItem.Selected = true;
                    Debug.WriteLine("Default is: " + user.StateID);
                }
                stateDescs.Add(sItem);
            });

            ViewBag.roleDescs = roleDescs;
            ViewBag.stateDescs = stateDescs;
            return View(user);
        }

        // POST: User/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, [Bind(Include = "RoleViewModel, StateViewModel")] UserViewModel user, int[] userNewAppIDs)
        {
            
            try
            {
                userLoader.updateUser(id, user, userNewAppIDs);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }



    }
}

686Final/Views/User/CurrentUser.cshtml
@model Common.UserViewModel

<div>
    <h4>User and Applications</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.UserID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EmailAddress)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EmailAddress)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastLoginDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastLoginDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StateViewModel.StateDescript)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StateViewModel.StateDescript)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RoleViewModel.RoleDescript)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RoleViewModel.RoleDescript)
        </dd>

    </dl>
</div>


<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.ApplicationViewModel.ElementAt(0).AppID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ApplicationViewModel.ElementAt(0).AppDescription)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ApplicationViewModel.ElementAt(0).AppType)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ApplicationViewModel.ElementAt(0).AppDateCreated)
        </th>
    </tr>

    @foreach (var item in Model.ApplicationViewModel)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.AppID)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AppDescription)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AppType)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AppDateCreated)
            </td>
            <td>
               @Html.ActionLink("View Errors", "AppErrors", "Error", new { appID = item.AppID }, null)
            </td>

        </tr>
    }

</table>


686Final/Views/User/Details.cshtml
@model Common.UserViewModel

<div>
    <h4>UserViewModel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.UserID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EmailAddress)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EmailAddress)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastLoginDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastLoginDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StateViewModel.StateDescript)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StateViewModel.StateDescript)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RoleViewModel.RoleDescript)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RoleViewModel.RoleDescript)
        </dd>

    </dl>
</div>


<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.ApplicationViewModel.ElementAt(0).AppID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ApplicationViewModel.ElementAt(0).AppDescription)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ApplicationViewModel.ElementAt(0).AppType)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ApplicationViewModel.ElementAt(0).AppDateCreated)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ApplicationViewModel.ElementAt(0).Active)
        </th>
    </tr>

    @foreach (var item in Model.ApplicationViewModel)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.AppID)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AppDescription)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AppType)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AppDateCreated)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Active)
            </td>
        </tr>
    }

</table>

<p>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    @Html.ActionLink("Back to List", "Index")
</p>

686Final/Views/User/Edit.cshtml
@model Common.UserViewModel

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>User Information</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.UserID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DisplayFor(model => model.UserID, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DisplayFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DisplayFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EmailAddress, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DisplayFor(model => model.EmailAddress, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EmailAddress, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastLoginDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DisplayFor(model => model.LastLoginDate, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StateViewModel.StateDescript, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.StateViewModel.StateID, ViewBag.stateDescs as IEnumerable<SelectListItem>, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StateViewModel.StateDescript, "", new { @class = "text-danger" })
            </div>
        </div>
        
        <div class="form-group">
            @Html.LabelFor(model => model.RoleViewModel.RoleDescript, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.RoleViewModel.RoleID, ViewBag.roleDescs as IEnumerable<SelectListItem>, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RoleViewModel.RoleDescript, "", new { @class = "text-danger" })
            </div>
        </div>

        <hr/>

        <h4>User Applications</h4>


        <table class="table">
            <tr>
                <th>
                    @Html.LabelFor(model => model.ApplicationViewModel.ElementAt(0).AppID)
                </th>
                <th>
                    @Html.LabelFor(model => model.ApplicationViewModel.ElementAt(0).AppDescription)
                </th>
                <th>
                    @Html.LabelFor(model => model.ApplicationViewModel.ElementAt(0).AppType)
                </th>
                <th>
                    @Html.LabelFor(model => model.ApplicationViewModel.ElementAt(0).AppDateCreated)
                </th>
                <th>
                    @Html.LabelFor(model => model.ApplicationViewModel.ElementAt(0).Active)
                </th>
            </tr>



            @foreach (var item in Model.ApplicationViewModel)
            {
                <tr>
                    
                    <td>
                        @Html.DisplayFor(modelItem => item.AppID)
                    </td>

                   
                    <td>
                        @Html.DisplayFor(modelItem => item.AppDescription)
                        @Html.ValidationMessageFor(modelItem => item.AppDescription, "", new { @class = "text-danger" })
                    </td>

                    
                    <td>
                        @Html.DisplayFor(modelItem => item.AppType)
                        @Html.ValidationMessageFor(modelItem => item.AppType, "", new { @class = "text-danger" })
                    </td>

                    <td>
                        @Html.DisplayFor(modelItem => item.AppDateCreated)
                           
                    </td>

                    <td>
                       
                        @Html.ValidationMessageFor(modelItem => item.Active, "", new { @class = "text-danger" })
                        <input type="checkbox" name="userNewAppIDs" value="@item.AppID" @(Html.Raw(item.Active ? "checked=\"checked\"" : ""))>

                    </td>

                </tr>

            }

        </table>

        <div class="form-group">
            <div class="col-md-offset-11">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

686Final/Views/User/Index.cshtml
@model IEnumerable<Common.UserViewModel>

<p>
    @Html.ActionLink("Application Manager", "Index", "Application", new { }, null)
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.UserID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LastName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EmailAddress)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LastLoginDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.StateID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.RoleID)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.UserID)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.FirstName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.LastName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.EmailAddress)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.LastLoginDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.StateID)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.RoleID)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id = item.UserID }) |
            @Html.ActionLink("Details", "Details", new { id = item.UserID }) |
        </td>
    </tr>
}

</table>